### PR TITLE
fix: Some parameter attributes were lost on JSON request. 

### LINKED ISSUE #472: [BUG] ActiveMQ uri building incorrect?
**Describe the bug**
When defining an activemq endpoint the code generated seems wrong. It displays `uri: activemq:myQueueName:queue` but if I understand the component documentation correctly it should be `uri: activemq:queue:myQueueName` or in this case just `uri: activemq:myQueueName` because if it is a queue you can skip specifying it. (see https://camel.apache.org/components/3.18.x/activemq-component.html)

**To Reproduce**
1. Select integration type "Camel Route"
2. Select activemq component as starting point
3. Open the code editor
4. see the URI

**Expected behavior**
See description of the bug and the linked component documentation.

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. "Linux 5.10.0-9-amd64#1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux"]
 - Output of the mvn -version` command
 - Kaoto Version [e.g. 1.0]

**Additional context**

### PR DESCRIPTION
**Pull request by Delawen**
Fixes #472

Some of the attributes of the parameters were lost (because we don't send to the frontend as they are useless for the ui, we should even remove more but that's another issue). So when trying to build the path parameters uri from the json info, we didn't have everything we needed.

Now we are just interested in the values sent from the ui, the rest is refreshed from the catalog.

This also comes with the extra feature of making sure the ui didn't make up weird parameters or even weird connectors on its own. If it is not on the catalog, it is not valid.

### CODE REVIEW

File: api/src/test/java/io/kaoto/backend/api/resource/v1/IntegrationsResourceTest.java [hunk 1]
```diff
@@ -172,25 +169,93 @@ void complexEIP() throws URISyntaxException, IOException {
     @Test
     void amqAmq() throws Exception {
         String yaml = Files.readString(Path.of(
```
Comment (Delawen) [inline api/src/test/java/io/kaoto/backend/api/resource/v1/IntegrationsResourceTest.java:171]: I also made this test stronger while trying to understand where the bug comes from. So win-win.

File: api/src/test/resources/io/kaoto/backend/api/resource/amq-amq.yaml [hunk 2]
```diff
@@ -1,5 +1,5 @@
 - from:
-    uri: activemq:null:queue
```
Comment (Delawen) [inline api/src/test/resources/io/kaoto/backend/api/resource/amq-amq.yaml:2]: Made this test strong while debugging to check what happened with the path parameters.

File: kamelet-support/src/main/java/io/kaoto/backend/KamelPopulator.java [hunk 3]
```diff
@@ -266,18 +273,26 @@ public From getFlow(final List<Step> steps) {
...
-                    uri.append(p.getPathSeparator());
-                    uri.append(p.getValue() != null ? p.getValue() : p.getDefaultValue());
-                } else if (p.getValue() != null) {
-                    params.put(p.getId(), p.getValue().toString());
+            //We need to make sure parameters attributes coming from the frontend are complete and right
+            //The only important thing we need to take from them is the value, the rest should be as default
+            HashMap<String, Object> values = new HashMap<>();
+            s.getParameters().stream().forEach(parameter -> values.put(parameter.getId(), parameter.getValue()));
+
+            //Now we can work with the parameters list
```
Comment (Delawen) [inline kamelet-support/src/main/java/io/kaoto/backend/KamelPopulator.java:284]: This is where the real change is. The rest is just dragging the catalog to this point.
