### PR TITLE
fix: expression object is filled with default values

### LINKED ISSUE #569: [BUG] `expression` object is filled with default values
**Describe the bug**
A variation of https://github.com/KaotoIO/kaoto-backend/issues/503

`expression` object is filled with default values after code sync

**To Reproduce**
1. Open source code editor
2. Paste this code
```yaml
- from:
    uri: timer:null
    steps:
      - choice:
          when:
            - expression:
                simple:
                  expression: choice
```
4. Click `sync your code`
5. YAML is updated with default values
```yaml
- from:
    uri: timer:null
    steps:
    - choice:
        when:
        - expression:
            simple:
              expression: choice
              trim: false
              result-type: 'null'
              id: 'null'
          steps: []
```

**Expected behavior**
Default values are wiped out

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. "Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux"]
 - Output of the mvn -version` command
 - Kaoto Version [e.g. 1.0]

**Additional context**

### PR DESCRIPTION
**Pull request by igarashitm**
Fixes: #569

### CODE REVIEW

**Review by Delawen — APPROVED** [review]

File: kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/expression/CSimple.java [hunk 1]
```diff
@@ -23,18 +23,18 @@ public CSimple() {
     }
 
     public CSimple(Map map) {
-        if (map.containsKey(EXPRESSION_LABEL)) {
```
Comment (Delawen) [inline kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/expression/CSimple.java:26]: Are we sure we will always have the key in the map? (I see it works on the tests, but I am not 100% sure)

Comment (Delawen) [reply kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/expression/CSimple.java:26]: Thinking on using `getOrDefault` instead of `get`

**Comment by Delawen** [comment]
Plus conflicts, sorry :(

**Review by Delawen — CHANGES_REQUESTED** [review]
Change `get` with `getOrDefault(key, null)` to avoid potential keys missing.

File: kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/expression/CSimple.java (hunk 1 above)
Comment (igarashitm) [reply kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/expression/CSimple.java:26]: `get` is promised to return `null` if there's no entry
https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#get-java.lang.Object-

**Review by Delawen — APPROVED** [review]
