### PR TITLE
fix: make sure names are kubernetes compatible names

### LINKED ISSUE #723: [BUG] Invalid `/metadata/name` format for generated ids of Integration
**Describe the bug**
The auto-generated `/metadata/name` uses upper case character which is not allowed

> [tomo@p1 camel-k]$ kubectl apply -f example.integration.yaml
The Integration "Integration1687900965845" is invalid: metadata.name: Invalid value: "Integration1687900965845": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**To Reproduce**
1. Choose Integration or Kamelet
2. deploy generated YAML onto k8s

**Expected behavior**
Use lowercase

### PR DESCRIPTION
**Pull request by Delawen**
Fixes #723

### CODE REVIEW

File: api/src/test/java/io/kaoto/backend/api/resource/v2/IntegrationsResourceTest.java [hunk 1]
```diff
@@ -413,6 +413,7 @@ void uniqueName() throws IOException {
                 .entrySet();
         assertEquals(flows.flows().size(), ids.size());
         assertTrue(ids.stream().allMatch(id -> id.getValue() == 1l));
+            assertTrue(ids.stream().allMatch(id ->Pattern.matches( "([A-Za-z0-9])+", id.getKey().toString())));
```
Comment (lordrip) [inline api/src/test/java/io/kaoto/backend/api/resource/v2/IntegrationsResourceTest.java:416]:
```suggestion
        assertTrue(ids.stream().allMatch(id ->Pattern.matches( "([A-Za-z0-9])+", id.getKey().toString())));
```

File: api/src/main/java/io/kaoto/backend/api/resource/v2/IntegrationsResource.java [hunk 2]
```diff
@@ -146,7 +146,8 @@ private static void ensureUniqueNames(FlowsWrapper answer) {
             }
             //Make sure there is an id/name assigned to all flows
             if (!flow.getMetadata().containsKey(name)) {
-                flow.getMetadata().put(name, flow.getDsl() + System.currentTimeMillis());
+                flow.getMetadata().put(name,
+                        flow.getDsl().toLowerCase().replaceAll(" ", "") + System.currentTimeMillis());
```
Comment (lordrip) [inline api/src/main/java/io/kaoto/backend/api/resource/v2/IntegrationsResource.java:150]: Instead of using a timestamp, could we use a 4 digits random number instead?

**Review by lordrip — APPROVED** [review]

File: api/src/main/java/io/kaoto/backend/api/resource/v2/IntegrationsResource.java (hunk 2 above)
Comment (Delawen) [reply api/src/main/java/io/kaoto/backend/api/resource/v2/IntegrationsResource.java:150]: Timestamp is sure to not be repeated, I feel safer with timestamp :laughing:

Comment (Delawen) [reply api/src/main/java/io/kaoto/backend/api/resource/v2/IntegrationsResource.java:150]: Is it very ugly on the frontend side then?

Comment (Delawen) [reply api/src/main/java/io/kaoto/backend/api/resource/v2/IntegrationsResource.java]: Added a random integer.

**Review by syednabilashraf — APPROVED** [review]

**Comment by Delawen** [comment]
Thank you @syednabilashraf for checking!
