### PR TITLE
fix: Beans UI support for Integration and Kamelet

### LINKED ISSUE #717: [BUG] 2nd Integration CRD is added if metadata exists on JSON>YAML
**Describe the bug**
When UI sends integration JSON with topmost `metadata` defined, backend returns 2 Integration CRDs.

#### Request
```json
{
    "flows": [
        {
            "id": "route-2788",
            "dsl": "Integration",
            "description": "",
            "metadata": {},
            "params": [],
            "steps": []
        }
    ],
    "properties": {},
    "metadata": {
        "beans": [
            {}
        ]
    }
}
```

#### Response
```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: Integration1687876469547
spec:
  flows:
  - from:
      uri: null
      steps: []
---
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: ''
spec:
  flows:
  - from:
      uri: null
      steps: []
```

**To Reproduce**
1. Choose `Integration`
2. Click `Beans`
3. Click `Add new`
4. See browser network tab

**Expected behavior**
No 2nd Integration CRD, and beans are added into `/spec/flows/beans`

### LINKED ISSUE #742: Beans UI doesn't work properly for Kamelet local beans
### Describe the Bug

Beans UI doesn't work properly for Kamelet local `beans`. The root cause would be that the Kamelet local beans are placed under `flows[0].metadata`, as opposed to the `Camel Route` which has `beans` as a topmost metadata in `FlowsWrapper.metadata`. But the behavior is broken beyond that.

If you click `Add beans` button in Beans UI, the 2nd `Kamelet` CRD is added with `---` separator. It should never display multiple Kamelet CRD since we don't support switching between multiple context, i.e. Kamelet1 beans and Kamelet2 beans are completely separate and not visible each other, thus Beans UI has to switch the context.
Screenshot from 2023-06-26 18-23-47

### Steps to Reproduce the Bug or Issue

1. Choose `Kamelet` in `New Route` dropdown
2. Open Beans UI
3. Click `Add beans` button

### Screenshots or Videos

_No response_

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

### PR DESCRIPTION
**Pull request by igarashitm**
Fixes: #717 
Screenshot from 2023-06-30 18-54-47

Fixes: #742
Screenshot from 2023-06-30 18-46-17

### CODE REVIEW

File: api/src/test/java/io/kaoto/backend/api/resource/v2/IntegrationsResourceTest.java [hunk 1]
```diff
@@ -369,10 +369,11 @@ void beans() throws Exception {
     }
 
     @ParameterizedTest
-    @ValueSource(strings = {"Camel Route#route-multi.yaml", "KameletBinding#kamelet-binding-multi.yaml",
```
Comment (Delawen) [inline api/src/test/java/io/kaoto/backend/api/resource/v2/IntegrationsResourceTest.java:372]: Why are we removing the kamelet bindings here?

File: kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/Bean.java [hunk 2]
```diff
@@ -29,7 +29,7 @@
  value: 'org.postgresql.Driver'
  * ```
  */
-@JsonPropertyOrder({"name", "type", "property"  })
+@JsonPropertyOrder({"name", "type", "properties", "property"  })
```
Comment (Delawen) [inline kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/Bean.java:32]: If we are going to convert all to property instead of properties, maybe it makes sense not to mention it here?

**Review by Delawen — CHANGES_REQUESTED** [review]

File: kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/Bean.java (hunk 2 above)
Comment (igarashitm) [reply kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/Bean.java:32]: Aren't we converting to `properties`? Although both of them will stay supported, the recommended way is `properties` which is same with Camel Route/Integration beans.

File: kamelet-support/src/test/java/io/kaoto/backend/api/service/step/parser/kamelet/KameletStepParserServiceTest.java [hunk 3]
```diff
@@ -175,6 +180,8 @@ void deepParseInvalid(String resourcePath) throws IOException {
                 .hasMessageContaining("Wrong format provided. This is not parseable by us.");
     }
 
+    @Disabled("Multiple CRD requires to represent multiple contexts,"
```
[the remark this answers is not in the document]
Comment (igarashitm) [reply kamelet-support/src/test/java/io/kaoto/backend/api/service/step/parser/kamelet/KameletStepParserServiceTest.java]: done :+1:

File: api/src/test/java/io/kaoto/backend/api/resource/v2/IntegrationsResourceTest.java (hunk 1 above)
Comment (igarashitm) [reply api/src/test/java/io/kaoto/backend/api/resource/v2/IntegrationsResourceTest.java:372]: ugh was by mistake, got it back.

File: kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/Bean.java (hunk 2 above)
Comment (Delawen) [reply kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/Bean.java:32]: Uh... maybe I was remembering right. Yes.

**Review by Delawen — APPROVED** [review]
