### PR TITLE
fix: Integration/Kamelet/KameletBinding: Put name and description in FlowsWrapper.metadata

### LINKED ISSUE #751: [BUG] Kamelet `name` and `description` support under template
**Describe the bug**
Kamelet `/spec/template/description` is removed on YAML>JSON. It deploys fine and preserved at runtime.

#### YAML source
```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  labels:
    camel.apache.org/kamelet.type: action
  name: route-9956-action
spec:
  definition:
    properties: {}
    title: ''
  dependencies:
  - camel:core
  - camel:timer
  - camel:log
  template:
    description: foobar
    from:
      uri: timer:test
      steps:
      - to:
          uri: 'log:'
```

#### kamel describe deployed
```yaml
Name:	route-9956-action
Namespace:	default
Labels:	camel.apache.org/kamelet.type=action
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"camel.apache.org/v1alpha1","kind":"Kamelet","metadata":{"annotations":{},"labels":{"camel.apache.org/kamelet.type":"action"},"name":"route-9956-action","namespace":"default"},"spec":{"definition":{"properties":{},"title":""},"dependencies":["camel:core","camel:timer","camel:log"],"template":{"description":"foobar","from":{"steps":[{"to":{"uri":"log:"}}],"uri":"timer:test"}}}}
Creation Timestamp:	Wed, 05 Jul 2023 16:40:40 -0400
Phase:	Ready
Definition:
  Title:	
  Description:
    
Template:
  {"description":"foobar","from":{"steps":[{"to":{"uri":"log:"}}],"uri":"timer:test"}}
Dependencies:	
  camel:core
  camel:timer
  camel:log
```

**To Reproduce**
1. Paste the YAML source above
2. Click sync button
3. description is removed

**Expected behavior**
description is preserved

#### UPDATE:
1. It turned out the `/spec/template/description` doesn't exist for camel 3.x, it seems to have been added in camel 4. `/spec/template/id` does exist on the other hand
2. There're also `/spec/template/route/id` and `/spec/template/route/description`
3. If `/spec/template/id` and `/spec/template/route/id` is specified, the Kamelet cannot be found from KameletBinding - https://github.com/apache/camel-k/issues/4546

### PR DESCRIPTION
**Pull request by igarashitm**
Fixes: #751

### CODE REVIEW

File: api/src/test/java/io/kaoto/backend/api/resource/v2/IntegrationsResourceTest.java [hunk 1]
```diff
@@ -367,7 +367,7 @@ void beans() throws Exception {
     }
 
     @ParameterizedTest
-    @ValueSource(strings = {"Camel Route#route-multi.yaml", "KameletBinding#kamelet-binding-multi.yaml",
```
Comment (Delawen) [inline api/src/test/java/io/kaoto/backend/api/resource/v2/IntegrationsResourceTest.java:370]: Why remove this KameletBinding? If it is because it is multi, then we should use one that is not multi. But not remove Kamelet Binding from here, shouldn't we?

**Review by Delawen — CHANGES_REQUESTED** [review]

**Comment by lordrip** [comment]
What do you think of adding a default `name` when creating a new FlowsWraper? is this a good idea?

File: api/src/test/java/io/kaoto/backend/api/resource/v2/IntegrationsResourceTest.java (hunk 1 above)
Comment (igarashitm) [reply api/src/test/java/io/kaoto/backend/api/resource/v2/IntegrationsResourceTest.java:370]: Ah OK, this is the only one KameletBinding here... added the other one.

**Review by Delawen — APPROVED** [review]
