### PR TITLE
fix: Support duration in parameters

### LINKED ISSUE #1432: Support `duration` type of fields in config panel
### Please describe the feature that you want to propose

Currently, duration types are not supported, only the name of the field is displayed but it is not possible to define it.

This is a common type, used for instance for `period` on `timer`. See https://camel.apache.org/manual/faq/how-do-i-specify-time-period-in-a-human-friendly-syntax.html

Ideas to split in iterations:
- Provide a text field
- Provide a tooltip on/close to the text field
- Provide validation on the text field. The Camel Catalog is providing [api to validate duration](https://github.com/apache/camel/blob/05595854aadb81ccb408c1ca8c3c28c4dc835ec3/core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/AbstractCamelCatalog.java#L149)
- Provide a specific widget

### PR DESCRIPTION
**Pull request by Delawen**
Fixes https://github.com/KaotoIO/kaoto-ui/issues/1432

WIP until #602 is merged. Then, rebase and test.

### CODE REVIEW

File: kamelet-support/src/test/java/io/kaoto/backend/metadata/parser/step/camelroute/CamelRouteParseCatalogTest.java [hunk 1]
```diff
@@ -140,6 +140,17 @@ private void assertBrowseJsonHasBeenParsedCorrectly(
         );
     }
 
+    @Test
+    void checkDuration() {
+        String camelZip = "resource://camel-3.19.0.zip";
```
Comment (apupier) [inline kamelet-support/src/test/java/io/kaoto/backend/metadata/parser/step/camelroute/CamelRouteParseCatalogTest.java:145]: migth be worthy to extract the camelZip as a constant as it is used several times in the class

File: kamelet-support/src/test/java/io/kaoto/backend/metadata/parser/step/camelroute/CamelRouteParseCatalogTest.java [hunk 2]
```diff
@@ -140,6 +140,17 @@ private void assertBrowseJsonHasBeenParsedCorrectly(
...
+        InMemoryCatalog<Step> catalog = new InMemoryCatalog<>();
+        ParseCatalog<Step> camelParser = parseCatalog.getParser(camelZip);
+        assertTrue(catalog.store(camelParser.parse().join()));
+        Step consumer = catalog.searchByID("timer-consumer");
+        consumer.getParameters().stream().parallel()
+                .anyMatch(p -> p.getId().equalsIgnoreCase("delay") && p  instanceof StringParameter);
```
Comment (apupier) [inline kamelet-support/src/test/java/io/kaoto/backend/metadata/parser/step/camelroute/CamelRouteParseCatalogTest.java:151]: an assertion is missing

Comment (apupier) [inline kamelet-support/src/test/java/io/kaoto/backend/metadata/parser/step/camelroute/CamelRouteParseCatalogTest.java:151]: extra space
```suggestion
        consumer.getParameters().stream().parallel()
                .anyMatch(p -> p.getId().equalsIgnoreCase("delay") && p instanceof StringParameter);
```

**Review by apupier — CHANGES_REQUESTED** [review]
it might be interesting to provide a test for `long` too given that it was implemented also in type same PR than for `duration`

**Comment by Delawen** [comment]
Added a check for one of the `long` properties in the `activemq` component.

File: kamelet-support/src/test/java/io/kaoto/backend/metadata/parser/step/camelroute/CamelRouteParseCatalogTest.java [hunk 3]
```diff
@@ -140,13 +140,25 @@ private void assertBrowseJsonHasBeenParsedCorrectly(
...
+    void checkDuration() {
+        InMemoryCatalog<Step> catalog = new InMemoryCatalog<>();
+        ParseCatalog<Step> camelParser = parseCatalog.getParser(CAMEL_ZIP);
+        assertTrue(catalog.store(camelParser.parse().join()));
+        Step consumer = catalog.searchByID("timer-consumer");
+        assertTrue(consumer.getParameters().stream().parallel()
+                .anyMatch(p -> p.getId().equalsIgnoreCase("delay") && p instanceof StringParameter));
+        Step activemq = catalog.searchByID("activemq-action");
+        assertTrue(activemq.getParameters().stream().parallel()
+                .anyMatch(p -> p.getId().equalsIgnoreCase("deliveryDelay") && p instanceof NumberParameter));
```
Comment (apupier) [inline kamelet-support/src/test/java/io/kaoto/backend/metadata/parser/step/camelroute/CamelRouteParseCatalogTest.java:153]: the check of the `long` doesn't match the name of the test. i think it would better to provide 2 different tests

Comment (apupier) [reply kamelet-support/src/test/java/io/kaoto/backend/metadata/parser/step/camelroute/CamelRouteParseCatalogTest.java:153]: and realizing that there was also the `numeric` which was added itn he same PR; So better with 3 tests

Comment (Delawen) [reply kamelet-support/src/test/java/io/kaoto/backend/metadata/parser/step/camelroute/CamelRouteParseCatalogTest.java:153]: Changed the name of the function.
