### PR TITLE
fix: when the content of the path param contains the path separator

### LINKED ISSUE #576: [BUG] filepath of AtlasMap uri is wiped out on `sync code`
**Describe the bug**

**To Reproduce**
1. Add a step
2. Add AtlasMap step
3. Select AtalsMap step
4. In Resource URi, provide a file path like `file:/etc/camel/resources/transform.adm` (inspired from q[uarkus superheroes example](https://github.com/pprosser-redhat/quarkus-super-heroes/blob/c530dd797f0ab35e50a0c07e6cf7cb4ab7c75a14/camelkfordebezium/camelformessaging/messaging.camel.yaml#L20))
5. Open source editor
6. Click on Sync code
7. --> only `file` is left

**Expected behavior**

the full path must be kept

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
OperateFirst

**Additional context**

### PR DESCRIPTION
**Pull request by Delawen**
Fixes #576

### CODE REVIEW

**Review by apupier — COMMENTED** [review]
this is a tricky use case, a test seems very important to avoid regression.

**Comment by Delawen** [comment]
> this is a tricky use case, a test seems very important to avoid regression.

Test added.

File: api/src/test/java/io/kaoto/backend/api/resource/v1/IntegrationsResourceTest.java [hunk 1]
```diff
@@ -304,6 +306,7 @@ void scriptStep() throws Exception {
                 .statusCode(Response.Status.OK.getStatusCode());
 
         var flow = res.extract().body().as(Integration.class);
+        assertEquals(2, flow.getSteps().size());
```
Comment (Delawen) [inline api/src/test/java/io/kaoto/backend/api/resource/v1/IntegrationsResourceTest.java:309]: This equals are because on the first run these tests failed and I was wondering why... and well, another check is not bad.

**Review by apupier — APPROVED** [review]
first iteration with a single time the path separator reused is working but when there are several it is not. Opening another issue to handle the more generic use case. See #591
