### PR TITLE
617 Fix expression support with native build

### LINKED ISSUE #617: [BUG] Native build backend wipes out the expression content in verbose dialect
**Describe the bug**
While it's preserved with `quarkus:dev`, with native build, the expression content is wiped out with the `/expression/simple/expression` version of a dialect.

**To Reproduce**
1. Paste this YAML
```yaml
- from:
    uri: "timer:trigger-gitter-streaming"
    parameters:
        repeatCount: 1
    steps:
        - log:
              message: Opening connection to Gitter...
        - setHeader:
              name: Authorization
              expression:
                  simple:
                      expression: "Bearer {{token}}"
        - to:
              uri: >-
                  [https://gitter.ems.host/_matrix/client/v3/sync?filter={](https://gitter.ems.host/_matrix/client/v3/sync?filter=%7B)"account_data":{"not_types":["*"]},"room":{"account_data":{"not_types":["*"]},"rooms":["{{room}}"],"timeline":{"limit":1,"types":["m.room.message"]},"state":{"not_types":["*"]}
                  } }
        - log:
              message: Gitter HTTP Streaming started
```
2. Click on 'Sync your code'
3. With native build the expression is wiped out, while it's preserved with `quarkus:dev`
#### quarkus:dev
https://user-images.githubusercontent.com/265462/230142934-7db3d33e-c512-473a-839b-92d478478330.mp4

#### native
https://user-images.githubusercontent.com/265462/230142998-8cbfe843-94d7-4c9c-989e-5338cf96774d.mp4

**Expected behavior**
Native build should also preserve it

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. "Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux"]
 - Output of the mvn -version` command
 - Kaoto Version [e.g. 1.0]

**Additional context**

### PR DESCRIPTION
**Pull request by apupier**
* Fix expression support in native mode: the Expression related classes were missing from native build. Registered all of them for reflection. It might be possible to be more specific and register a single one. To be investigated and potentially improved in another iteration
* Provide native tests for Integrations resource:
  * it allows to have a non-regression test for #617 issue with expressions
  * extracted a single test from IntegrationsResourceTest which cannot be launch in Native mode because it is using @Inject to access internal services directly. it allows to inherit the native test class from IntegrationsResourceTest and play all of the existing tests in native
 
fixes #617
part of #437

### CODE REVIEW

File: api/src/test/java/io/kaoto/backend/api/resource/v1/IntegrationsResourceIT.java [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+
+import io.quarkus.test.common.http.TestHTTPEndpoint;
+import io.quarkus.test.junit.QuarkusIntegrationTest;
+
+@TestHTTPEndpoint(IntegrationsResource.class)
+@QuarkusIntegrationTest
+class IntegrationsResourceIT {
+
+	@Test
+	void expressionObject() throws Exception {
```
Comment (igarashitm) [inline api/src/test/java/io/kaoto/backend/api/resource/v1/IntegrationsResourceIT.java:25]: Could this be like `new IntegrationsResourceTest().expressionObject()`? we'd see refactorings around expression sooner and this test would be revised repeatedly, and keep them sync between JVM<>native test would help

Comment (apupier) [reply api/src/test/java/io/kaoto/backend/api/resource/v1/IntegrationsResourceIT.java:25]: it could be. the ideal would be to find a way to just inherit from the IntegrationsResourceTest and deal with the problem of the @Inject. Maybe need to separate few methods. Maybe just overriding the @before/@after methods. I provided an issue to tackle it some time ago https://github.com/KaotoIO/kaoto-backend/issues/437

**Review by igarashitm — APPROVED** [review]
Tested locally and verified the expression is preserved with native build :+1:

File: api/src/test/java/io/kaoto/backend/api/resource/v1/IntegrationsResourceIT.java (hunk 1 above)
Comment (igarashitm) [reply api/src/test/java/io/kaoto/backend/api/resource/v1/IntegrationsResourceIT.java]: Now it's perfect :+1:

**Review by igarashitm — APPROVED** [review]
double checked :+1: +1 to merge this before 1.0. The risk is minimal, just added quarkus annotation and tests.

File: api/src/test/java/io/kaoto/backend/api/resource/v1/IntegrationsResourceIT.java [hunk 2]
```diff
@@ -0,0 +1,8 @@
+package io.kaoto.backend.api.resource.v1;
+
+import io.quarkus.test.junit.QuarkusIntegrationTest;
+
+@QuarkusIntegrationTest
```
Comment (Delawen) [inline api/src/test/java/io/kaoto/backend/api/resource/v1/IntegrationsResourceIT.java:5]: Oh, so simple! I like it!

**Review by Delawen — APPROVED** [review]
